ENH: add subtypes for Type I SNe; clean up subtypes for Type II
profjsb/timedomain-taxonomy pull request #11
Opened 2020-11-19 20:19 UTC by adamamiller

I've added several common subtypes for SNe I (Ibn, Ia-CSM, Ia-91T, etc), cleaned up the Type II hierarchy, and added the class Ca-rich. 

Note "Ca-rich" is bit a of strange class as there are Ib and Ic that are Ca-rich (and even some Ia). For now Ca-rich is a separate class entirely, but this could be changed.

2020-11-19 20:59 UTC, profjsb requested changes
Looks good. Please bump the version number in `tdtax/__init__.py`. Few small edits suggested as well.

2020-11-19 20:59 UTC, profjsb commented on tdtax/supernovae.yaml
> +        other names: [SN IcBL, SN Ic-BL, hypernova, broad line supernova]
```suggestion
        other names: [SN IcBL, SN Ic-BL, hypernova, broad-lined supernova]
```

2020-11-19 20:59 UTC, profjsb commented on tdtax/supernovae.yaml
> +  other names: [Ca strong]
add a newline at end:
```suggestion
  other names: [Ca strong]
  
```

2020-11-19 22:00 UTC, adamamiller commented
Requested changes done. Ready for PR

2020-11-20 01:37 UTC, profjsb approved these changes

2020-11-20 01:37 UTC, merged