SNe Id, Idn, Ie, Ien, and LRN
profjsb/timedomain-taxonomy pull request #25
Opened 2024-10-07 17:12 UTC by Theodlz

This PR adds:
-  a subtype of Novae: Luminous Red Nova (LRN)
- 4 new SNe subtypes: Id, Idn, Ie, Ien

This is based on user requests, that need this in the Sitewide taxonomy of SkyPortal (that reads its content from this repo's main branch).

2024-10-07 17:12 UTC, Theodlz commented
Feel free to make any changes!

2024-10-07 17:12 UTC, Theodlz commented
@profjsb

2024-10-08 02:51 UTC, profjsb requested changes
Looks good. Tiny change requested.

2024-10-08 02:51 UTC, profjsb commented on tdtax/supernovae.yaml
> +    - https://arxiv.org/pdf/2409.02054
```suggestion
    - https://arxiv.org/abs/2409.02054
```

2024-10-08 02:51 UTC, profjsb commented on tdtax/supernovae.yaml
> +    - https://arxiv.org/pdf/2409.02054
```suggestion
    - https://arxiv.org/abs/2409.02054
```

2024-10-08 16:52 UTC, profjsb approved these changes
LGTM

2024-10-08 16:52 UTC, merged